before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/tfcw
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    flags:
      - -trimpath
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: '{{ .ProjectName }}_edge_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

release:
  disable: true

snapcrafts:
  - summary: Terraform Cloud Wrapper
    description: Manage Terraform Cloud configuration programatically.
    license: Apache-2.0
    confinement: strict
    grade: devel
    apps:
      tfcw:
        plugs: [home, network]

dockers:
  - image_templates:
      - 'docker.io/mvisonneau/tfcw:latest-amd64'
      - 'ghcr.io/mvisonneau/tfcw:latest-amd64'
      - 'quay.io/mvisonneau/tfcw:latest-amd64'
    ids: [tfcw]
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/tfcw
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/tfcw
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  - image_templates:
      - 'docker.io/mvisonneau/tfcw:latest-arm64'
      - 'ghcr.io/mvisonneau/tfcw:latest-arm64'
      - 'quay.io/mvisonneau/tfcw:latest-arm64'
    ids: [tfcw]
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mvisonneau/tfcw
      - --label=org.opencontainers.image.source=https://github.com/mvisonneau/tfcw
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: docker.io/mvisonneau/tfcw:latest
    image_templates:
      - docker.io/mvisonneau/tfcw:latest-amd64
      - docker.io/mvisonneau/tfcw:latest-arm64

  - name_template: ghcr.io/mvisonneau/tfcw:latest
    image_templates:
      - ghcr.io/mvisonneau/tfcw:latest-amd64
      - ghcr.io/mvisonneau/tfcw:latest-arm64

  - name_template: quay.io/mvisonneau/tfcw:latest
    image_templates:
      - quay.io/mvisonneau/tfcw:latest-amd64
      - quay.io/mvisonneau/tfcw:latest-arm64

signs:
  - artifacts: checksum
    args:
      [
        '-u',
        'C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]

checksum:
  name_template: '{{ .ProjectName }}_edge_sha512sums.txt'
  algorithm: sha512

changelog:
  skip: true
